### ISSUE TITLE
vmchat stop to work suddenly.

### ISSUE THREAD

**Issue by mandamas** [vidyamantra/moodle-local_vmchat#13]

**Comment by mandamas** [comment]
Looking at the inspector console this is the error founded
wss://Error : DB 1029
iolib.js:1 Uncaught DOMException: Failed to construct 'WebSocket': The URL 'wss://Error : DB 1029' is invalid.
    at Object.wsconnect (http://virtual.uflo.edu.ar/local/vmchat/bundle/chat/bundle/io/build/iolib.js:1:245)
    at Object.init (http://virtual.uflo.edu.ar/local/vmchat/bundle/chat/bundle/io/build/iolib.js:1:132)
    at HTMLDocument.<anonymous> (http://virtual.uflo.edu.ar/lib/requirejs.php/1491671188/core/first.js:20:1387)
    at j (http://virtual.uflo.edu.ar/lib/javascript.php/1491671188/lib/jquery/jquery-1.11.3.min.js:25:274)
    at Object.fireWith [as resolveWith] (http://virtual.uflo.edu.ar/lib/javascript.php/1491671188/lib/jquery/jquery-1.11.3.min.js:25:1091)
    at Function.ready (http://virtual.uflo.edu.ar/lib/javascript.php/1491671188/lib/jquery/jquery-1.11.3.min.js:25:2925)
    at J (http://virtual.uflo.edu.ar/lib/javascript.php/1491671188/lib/jquery/jquery-1.11.3.min.js:27:91)
wsconnect @ iolib.js:1
init @ iolib.js:1
(anonymous) @ first.js:20
j @ jquery-1.11.3.min.js:25
fireWith @ jquery-1.11.3.min.js:25
ready @ jquery-1.11.3.min.js:25
J @ jquery-1.11.3.min.js:27

Any idea about what happens ando how to solve??

Thank  you
